### ISSUE TITLE
Crash to desktop on joining multiplayer

### ISSUE THREAD

**Issue by jasonmcalpin** [Corben-SpacedOut/SEHeadTracking#4]
I am using client 1.199.025.
This works in single-player without issue. 
It was working in multiplayer for a while and about a week ago it started crashing. 

STEPS
Select NA #1 Server.
It sits on the loading screen then drops to the desktop.

I am including the settings and configs.

[HeadTrackingPlugin.log](https://github.com/Corben-SpacedOut/SEHeadTracking/files/7413768/HeadTrackingPlugin.log)
 
[SpaceEngineers_20211025_174147212.log](https://github.com/Corben-SpacedOut/SEHeadTracking/files/7413771/SpaceEngineers_20211025_174147212.log)

[HeadTrackingSettings.xml.txt](https://github.com/Corben-SpacedOut/SEHeadTracking/files/7413777/HeadTrackingSettings.xml.txt)

[SpaceEngineers.cfg.txt](https://github.com/Corben-SpacedOut/SEHeadTracking/files/7413789/SpaceEngineers.cfg.txt)

**Comment by jarno-r** [comment]
The plugin now has an update version 0.2.0.1, which hopefully fixes the issue. Please let us know if it still crashes.

**Comment by jasonmcalpin** [comment]
Plugin is working again. Thank you.
